# Generated by Django 6.0.4 on 2026-05-04 14:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_boutiques', models.IntegerField(default=1)),
                ('max_utilisateurs', models.IntegerField(default=1)),
                ('rapports_avances', models.BooleanField(default=False)),
                ('premier_mois_offert', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('couleur', models.CharField(default='#3B82F6', max_length=30)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('email', 'Vérification email'), ('reset', 'Réinitialisation mot de passe')], max_length=10)),
                ('expire_le', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé'), ('en_attente', 'En attente de paiement')], default='en_attente', max_length=20)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('fin_periode_gratuite', models.DateField(blank=True, null=True)),
                ('prochain_prelevement', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='momoapi.pack')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Depot', 'Dépôt'), ('Retrait', 'Retrait'), ('Credit', 'Achat de crédit/forfait')], max_length=10)),
                ('operateur', models.CharField(choices=[('MTN', 'MTN'), ('Moov', 'Moov'), ('Celtiis', 'Celtiis')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_client', models.CharField(max_length=30)),
                ('nom_client', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('remarque', models.TextField(blank=True)),
                ('type_credit', models.CharField(blank=True, choices=[('Credit', 'Crédit'), ('Forfait', 'Forfait')], max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='momoapi.boutique')),
                ('effectuee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MembreBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('gerant', 'Gérant'), ('admin', 'Administrateur')], default='gerant', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='momoapi.boutique')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('boutique', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_depots', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_retraits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_transferts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_commissions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('benefice_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='momoapi.boutique')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('boutique', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SoldeOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('MTN', 'MTN'), ('Moov', 'Moov'), ('Celtiis', 'Celtiis'), ('Caisse', 'Caisse')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes', to='momoapi.boutique')),
            ],
            options={
                'unique_together': {('boutique', 'operateur')},
            },
        ),
    ]
