# Generated by Django 6.0.4 on 2026-06-05 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momoapi', '0002_avis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('suppression', 'Suppression'), ('modification', 'Modification'), ('retrait', 'Retrait effectué'), ('depot', 'Dépôt effectué'), ('credit', 'Achat de crédit'), ('export', 'Export PDF'), ('info', 'Information')], default='info', max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='momoapi.boutique')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-cree_le'],
            },
        ),
    ]
