# Generated by Django 6.0.6 on 2026-08-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momoapi', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='fedapay_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
