# Generated by Django 6.0.6 on 2026-08-13 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momoapi', '0004_abonnement_fedapay_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSuppressionCompte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('raison', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traitée — compte supprimé'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de suppression de compte',
                'verbose_name_plural': 'Demandes de suppression de compte',
                'ordering': ['-cree_le'],
            },
        ),
    ]
