# Generated by Django 6.0.6 on 2026-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momoapi', '0005_demandesuppressioncompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandesuppressioncompte',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='demandesuppressioncompte',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
